[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.focused_match]
background = "#434c5e"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Iosevka Nerd Font"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = ""
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = ""
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cn"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B;"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B/"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B "
key = "Space"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000c"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[32;2u"
key = "Space"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Command"

[general]
live_config_reload = true

[mouse]
hide_when_typing = false


[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = """,â”‚`|:"' ()[]{}<>"""

[window]
decorations = "buttonless"
dynamic_title = true

[window.padding]
x = 2
y = 2

[keyboard]
